<?php
/**
 * @package Google Webfonts For Wootheme Framework
 */
/*
Plugin Name: Google Webfonts For Woo Framework
Plugin URI: https://github.com/academe/google-webfonts-for-woo-framework
Description: Adds all missing Google webfonts to the WooThemes themes that use the Woo Framework.
Version: 1.1.0
Author: Jason Judge
Author URI: http://www.academe.co.uk/
License: GPLv2 or later
*/

/*
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

/**
 * Set default settings on installation.
 * CHECKME: can this be wrapped with is_admin()?
 */

function GoogleWebfontsForWooFramework_activation()
{
    $google_api_key = get_option('google_api_key');
    if ($google_api_key === false) {
        add_option('google_api_key', '', false, true);
    }
}
register_activation_hook(__FILE__, 'GoogleWebfontsForWooFramework_activation');

/*
// PHP5.3 only.
register_activation_hook(__FILE__, function() {
    $google_api_key = get_option('google_api_key');
    if ($google_api_key === false) {
        add_option('google_api_key', '', false, true);
    }
});
*/

// Set the main plugin as a global object.
// There is a standard visitor version and an admin extended version.
if (is_admin()) {
    require(dirname(__FILE__) . '/google-webfonts-for-woo-framework-admin.php');
    $GWFC_OBJ = new GoogleWebfontsForWooFrameworkAdmin();
} else {
    $GWFC_OBJ = new GoogleWebfontsForWooFramework();
}

$GWFC_OBJ->init();

class GoogleWebfontsForWooFramework
{
    // The name of the cahce for the the fonts.
    public $trans_cache_name = 'google_webfonts_for_woo_framework_cache';

    // The time the fonts are cached for, before we fetch a new batch from Google.
    // TODO: make the time configurable, which would include "indefinite".
    public $cache_time = 43200; // 60*60*12 seconds = 12 hours

    // New fonts that this plugin brings to the framework.
    public $new_fonts = array();

    // A snapshot of fonts the framework includes.
    public $old_fonts = array();

    // The Google API URL we will fetch the font list from.
    public $api_url = 'https://www.googleapis.com/webfonts/v1/webfonts?key=';

    // Admin notice text.
    public $admin_notice = '';

    // Initilialise the plugin.
    public function init() {
        // Add the missing fonts to the non-admin pages too.
        // It needs to be an early action (5) to get in before the theme hook
        // that uses the font list.
        add_action('wp_head', array($this, 'action_set_fonts'), 5);
    }

    /**
     * Insert any missing Google fonts.
     * We would use a closure in PHP53, but this is the WordPress world.
     */

    public function sort_font_array($a, $b)
    {
        return ($a['name'] < $b['name']) ? -1 : 1;
    }

    /**
     * Insert any missing Google fonts.
     */

    public function action_set_fonts()
    {
        // This array is what the Woo Framework defines and uses.
        global $google_fonts;

        // If there is no global google fonts list, bail out.
        // It probably means the Woo framework has fundamentally changed the way it works.
        if (empty($google_fonts) || ! is_array($google_fonts)) return;

        // Take a snapshot, before we mess with the list, and sort them by name.
        // A closure would be nice here, but we are restricted to PHP 5.2 for WP.
        $this->old_fonts = $google_fonts;
        uasort($this->old_fonts, array($this, 'sort_font_array'));

        // Get the full list of Google fonts available.
        $all_fonts = $this->getGoogleFontsCached();

        if ( ! $all_fonts) return;

        // Completely replace the Woo Framework list with the new list.
        $google_fonts = $all_fonts;
    }

    /**
     * Get the full list of Google fonts, formated for Woo Framework.
     * We look first in the cache generated by the settings page, and then in
     * the local cache file if not in the cache.
     */

    public function getGoogleFontsCached()
    {
        // Transient caching.
        if (false === ($fonts = get_transient($this->trans_cache_name))) {
            $fonts = $this->getFallbackFonts();

            // Cache indefinitely. The cache will be refreshed on a visit to the settings page.
            if (!empty($fonts)) set_transient($this->trans_cache_name, $fonts);
        }

        return $fonts;
    }

    /**
     * Returns fallback font data, in the same format as getGoogleFontData().
     */

    public function getFallbackFontData()
    {
        $file = dirname(__FILE__) . '/fonts.json';

        if (is_readable($file)) {
            $data = file_get_contents($file);
            return json_decode($data, true);
        }

        return null;
    }

    /**
     * Returns fonts, formatted for Woo Framework, pulled from the local fallback file.
     */

    public function getFallbackFonts()
    {
        $font_data = $this->getFallbackFontData();
        $woo_fonts = array();

        if ( ! empty($font_date)) {
            foreach($font_data as $family => $variants) {
                $woo_fonts[] = array(
                    'name' => $family,
                    'variant' => ':' . implode(',', $this->abbreviateVariants($variants))
                );
            }
        }

        return $woo_fonts;
    }

    /**
     * Abbreviate an array of variants so it is as short as possible.
     */

    public function abbreviateVariants($variants)
    {
        return str_replace(
            array('400', '700'),
            array('r', 'b'),
            $variants
        );
    }
}


